services:
  - type: web
    name: agrivision-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: agrivision-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "1440"
      - key: OPEN_METEO_BASE_URL
        value: https://api.open-meteo.com/v1/forecast
      - key: CORS_ORIGINS
        value: '["*"]'

  - type: web
    name: agrivision-frontend
    runtime: static
    staticPublishPath: ./frontend
    buildCommand: ""
    plan: free

databases:
  - name: agrivision-db
    plan: free
    databaseName: agrivision
    user: agrivision_user